services:
  storage_app:
    container_name: storage_app
    tty: true
    stdin_open: true
    build: .
    depends_on:
      - mongo
    networks:
      - storage-net

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - storage-net

volumes:
  mongo-data:

networks:
  storage-net:
